const EWAY_ERRORS = {
  '100': 'Invalid Json',
  '101': 'Invalid Username',
  '102': 'Invalid Password',
  '103': 'Invalid Client-Id',
  '104': 'Invalid Client-Id',
  '105': 'Invalid Token',
  '106': 'Token Expired',
  '107': 'Authentication failed. Please inform the helpdesk',
  '108': 'Invalid login credentials',
  '109': 'Decryption of data failed',
  '110': 'Invalid Client-ID/Client-Secret',
  '111': 'GSTIN is not registered to this GSP',
  '112': 'IMEI does not belong to the user',
  '118': 'Try after 5 minutes',
  '238': 'Invalid auth token',
  '278': 'User GSTIN does not match with Transporter Id',
  '280': 'Status is not ACTIVE',
  '301': 'Invalid eway bill number',
  '311': 'Validity period lapsed, you cannot update vehicle details',
  '312': 'This eway bill is either not generated by you or cancelled',
  '315': 'Validity period lapsed, you cannot cancel this eway bill',
  '325': 'Could not retrieve data',
  '326': 'Could not retrieve GSTIN details for the given GSTIN number',
  '327': 'Could not retrieve data from HSN',
  '328': 'Could not retrieve transporter details from GSTIN',
  '329': 'Could not retrieve States List',
  '334': 'Could not retrieve user details by userid',
  '336': 'Could not retrieve transporter data by GSTIN',
  '337': 'Could not retrieve HSN details for the given HSN number',
  '338': 'Cannot update transporter details, current transporter already entered Part B',
  '339': 'You are not assigned to update the transporter details of this eway bill',
  '343': 'This e-way bill is cancelled',
  '344': 'Invalid eway bill number',
  '345': 'Validity period lapsed, you cannot reject the e-way bill',
  '351': 'Invalid state code',
  '357': 'Could not retrieve eway bill details, please contact helpdesk',
  '358': 'GSTIN in request header does not match the user GSTIN in payload',
  '363': 'E-way bill is not enabled for intra state movement for your state',
  '366': 'Bills generated today are not available yet, try yesterday or earlier',
  '393': 'Invalid GSTIN',
  '395': 'Eway Bill Number should be numeric only',
  '416': 'Date range exceeds allowed limit',
  '418': 'No record found',
  '604': 'E-way bill(s) already generated for the same document number',
  '658': 'Blocked - allowed number of requests exceeded for this duration',
};

export function getEwayErrorMessage(code) {
  if (!code) return null;
  const codeStr = String(code).trim();
  return EWAY_ERRORS[codeStr] || null;
}

export function formatEwayError(errorObj) {
  if (!errorObj) return 'Unknown error';
  const code = errorObj.errorCodes || errorObj.errorCode || errorObj.ErrorCode;
  const msg = errorObj.errorMessage || errorObj.ErrorMessage || errorObj.info;
  const known = getEwayErrorMessage(code);
  if (known) return `[${code}] ${known}`;
  if (msg) return `[${code || '?'}] ${msg}`;
  return `Error code: ${code || 'unknown'}`;
}

export default EWAY_ERRORS;
